before_install:
  - psql --version
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
  - sudo rm -rf /var/lib/postgresql
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main $PGVERSION >> /etc/apt/sources.list.d/postgresql.list"
  - sudo apt-get update -qq
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::="--force-confnew" install postgresql-$PGVERSION postgresql-server-dev-$PGVERSION
  - sudo chmod 777 /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo echo "local   all         postgres                          trust" > /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo echo "local   all         all                               trust" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo echo "host    all         all         127.0.0.1/32          trust" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo echo "host    all         all         ::1/128               trust" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart

before_script:
  - git clone -b $v8 --depth 10 git://github.com/v8/v8.git
  - cd v8 && git describe --always
  - make dependencies && make native library=shared -j8
  - sudo install -v --mode=0644 include/* /usr/include
  - sudo install -v --mode=0644 out/native/lib.target/libv8.so /usr/lib/libv8.so
  - sudo install -v out/native/d8 /usr/bin/d8
  - cd ..

env:
  matrix:
    - PGVERSION=9.3 v8=3.17
    - PGVERSION=9.3 v8=3.18
    - PGVERSION=9.3 v8=3.19
    - PGVERSION=9.3 v8=3.20
    - PGVERSION=9.3 v8=3.21
    - PGVERSION=9.2 v8=3.17
    - PGVERSION=9.2 v8=3.18
    - PGVERSION=9.2 v8=3.19
    - PGVERSION=9.2 v8=3.20
    - PGVERSION=9.2 v8=3.21
    - PGVERSION=9.1 v8=3.17
    - PGVERSION=9.1 v8=3.18
    - PGVERSION=9.1 v8=3.19
    - PGVERSION=9.1 v8=3.20
    - PGVERSION=9.1 v8=3.21
    - PGVERSION=9.0 v8=3.17
    - PGVERSION=9.0 v8=3.18
    - PGVERSION=9.0 v8=3.19
    - PGVERSION=9.0 v8=3.20
    - PGVERSION=9.0 v8=3.21

language: cpp
compiler:
  - clang
  - gcc

script: make
